name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: action/checkout@v2

    - name: lint
      uses: golanci/golangci-lint-action@v2

    - name:
      name: security
      uses: securego/gosec@master
      with:
        args: ./...

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...
