name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: lint
      uses: golangci/golangci-lint-action@v2
          
    - name: show lint errors
      run: golangci-lint run
        if: ${{ failure() }}

    - name: security
      uses: securego/gosec@master
      with:
        args: ./...
          - name: errors

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

#    - name: Test
#      run: go test -v ./...
